import {
  getModuleName,
  getInfo,
  getFields,
  queryActivities,
  queryActivitySummary,
  queryHeartRateSummary,
  querySleepSummary,
  queryHeartRateData,
  querySleepData,
  queryActivitySummariesAsync,
  queryHeartRateSummariesAsync,
  querySleepSummariesAsync,
  queryActivitiesAsync,
  queryHeartRateDataAsync,
  querySleepDataAsync,
  querySleepQualityAsync,
  querySleepQuality,
} from "./Data";
const Data = {
  getModuleName,
  getInfo,
  getFields,
  queryActivities,
  queryActivitySummary,
  queryHeartRateSummary,
  querySleepSummary,
  queryHeartRateData,
  querySleepData,
  queryActivitySummariesAsync,
  queryHeartRateSummariesAsync,
  querySleepSummariesAsync,
  queryActivitiesAsync,
  queryHeartRateDataAsync,
  querySleepDataAsync,
  querySleepQualityAsync,
  querySleepQuality,
};
export default Data;
