import {
  getModuleName,
  getInfo,
  queryActivities,
  queryActivitySummary,
  queryHearRataSummary,
  querySleepSummary,
  queryHearRateData,
  querySleepData,
  queryActivitySummariesAsync,
  queryHearRataSummariesAsync,
  querySleepSummariesAsync,
  queryActivitiesAsync,
  queryHearRateDataAsync,
  querySleepDataAsync,
} from "./Data";
const Data = {
  getModuleName,
  getInfo,
  queryActivities,
  queryActivitySummary,
  queryHearRataSummary,
  querySleepSummary,
  queryHearRateData,
  querySleepData,
  queryActivitySummariesAsync,
  queryHearRataSummariesAsync,
  querySleepSummariesAsync,
  queryActivitiesAsync,
  queryHearRateDataAsync,
  querySleepDataAsync,
};
export default Data;
