import {
  getModuleName,
  getInfo,
  getFields,
  queryPhotosDetails,
  queryTipsDetails,
  queryVenuesCategories,
  queryVenuesDetails,
  queryVenuesGetRecommendations,
  queryVenuesGetVenueList,
  queryVenuesHours,
  queryVenuesLikes,
  queryVenuesNextVenues,
  queryVenuesPhotos,
  queryVenuesSearch,
  queryVenuesSimilarVenues,
  queryVenuesSuggestSearch,
  queryVenuesTips,
  queryVenuesTrending,
} from "./Data";
const Data = {
  getModuleName,
  getInfo,
  getFields,
  queryPhotosDetails,
  queryTipsDetails,
  queryVenuesCategories,
  queryVenuesDetails,
  queryVenuesGetRecommendations,
  queryVenuesGetVenueList,
  queryVenuesHours,
  queryVenuesLikes,
  queryVenuesNextVenues,
  queryVenuesPhotos,
  queryVenuesSearch,
  queryVenuesSimilarVenues,
  queryVenuesSuggestSearch,
  queryVenuesTips,
  queryVenuesTrending,
};
export default Data;
