import {
  getModuleName,
  getInfo,
  getFields,
  queryGetactivity,
  queryGetgoals,
  queryGetintradayactivity,
  queryGetmeas,
  queryHeartList,
  queryHeart,
  querySleep,
  querySleepSummary,
  queryGetDevice,
  queryGetUser,
  queryGetWorkout,
} from "./Data";
const Data = {
  getModuleName,
  getInfo,
  getFields,
  queryGetactivity,
  queryGetgoals,
  queryGetintradayactivity,
  queryGetmeas,
  queryHeartList,
  queryHeart,
  querySleep,
  querySleepSummary,
  queryGetDevice,
  queryGetUser,
  queryGetWorkout,
};
export default Data;
